var datashed = [
	{
		id: '1',
		songs: '爱囚',
		name: '庄心妍',
		src: 'music/庄心妍 - 爱囚.mp3',
		alltime: '04:03',
		photo: 'images/zxy.jpg',
		lyrics: [
			{time: "00:00",lyric: "爱囚"},
			{time: "00:02", lyric: "词曲：胜屿" },
			{time: "00:06", lyric: "演唱：庄心妍" },
			{time: "00:19", lyric: "承诺 我已说出口" },
			{time: "00:23", lyric: "沉默 把时间偷走" },
			{time: "00:27", lyric: "回忆 它在我左右" },
			{time: "00:31", lyric: "计算着情仇" },
			{time: "00:35", lyric: "缘分 还没到尽头" },
			{time: "00:39", lyric: "只要 你继续牵手" },
			{time: "00:44", lyric: "我们 让爱慢慢成熟" },
			{time: "00:47", lyric: "直到天长地久" },
			{time: "00:52", lyric: "你松开我的手" },
			{time: "00:56", lyric: "心一直在颤抖" },
			{time: "00:59", lyric: "说着分手的理由" },
			{time: "01:01", lyric: "我全都不能接受 退后" },
			{time: "01:07", lyric: "为你放弃了我所有" },
			{time: "01:10", lyric: "只想你能回头" },
			{time: "01:12", lyric: "就当一切从新来过" },
			{time: "01:16", lyric: "你的吻还在我左右剌痛伤口" },
			{time: "01:20", lyric: "我已无力解开忧愁" },
			{time: "01:23", lyric: "为你放弃了我所有" },
			{time: "01:26", lyric: "只愿你能逗留" },
			{time: "01:29", lyric: "爱情虽然不能强求" },
			{time: "01:32", lyric: "就让我承受  许下那毒咒" },
			{time: "01:37", lyric: "我愿做你爱的死囚" },
			{time: "01:56", lyric: "缘分 还没到尽头" },
			{time: "02:00", lyric: "只要 你继续牵手" },
			{time: "02:04", lyric: "我们 让爱慢慢成熟" },
			{time: "02:08", lyric: "直到天长地久" },
			{time: "02:12", lyric: "你松开我的手" },
			{time: "02:16", lyric: "心一直在颤抖" },
			{time: "02:20", lyric: "说着分手的理由" },
			{time: "02:22", lyric: "我全都不能接受 退后" },
			{time: "02:28", lyric: "为你放弃了我所有" },
			{time: "02:31", lyric: "只想你能回头" },
			{time: "02:33", lyric: "就当一切从新来过" },
			{time: "02:36", lyric: "你的吻还在我左右剌痛伤口" },
			{time: "02:41", lyric: "我已无力解开忧愁" },
			{time: "02:44", lyric: "为你放弃了我所有" },
			{time: "02:47", lyric: "只愿你能逗留" },
			{time: "02:49", lyric: "爱情虽然不能强求" },
			{time: "02:53", lyric: "就让我承受  许下那毒咒" },
			{time: "02:58", lyric: "我愿做你爱的死囚" },
			{time: "03:01", lyric: "" },
			{time: "03:03", lyric: "为你放弃了我所有" },
			{time: "03:06", lyric: "只想你能回头" },
			{time: "03:08", lyric: "就当一切从新来过" },
			{time: "03:11", lyric: "你的吻还在我左右剌痛伤口" },
			{time: "03:16", lyric: "我已无力解开忧愁" },
			{time: "03:19", lyric: "为你放弃了我所有" },
			{time: "03:22", lyric: "只愿你能逗留" },
			{time: "03:24", lyric: "爱情虽然不能强求" },
			{time: "03:28", lyric: "就让我承受 许下那毒咒" },
			{time: "03:33", lyric: "我愿做你爱的死囚" },
			]
	},
    {
		id: '2',
		songs: '时间的力量',
		name: '尚雯婕',
		src: 'music/尚雯婕 - 时间的力量.mp3',
		alltime: '04:27',
		photo: 'images/swj.jpg',
		lyrics:[
			{time:"00:01", lyric:"时间的力量 time will tell"},
			{time:"00:04", lyric:"曲：尚雯婕"},
			{time:"00:06", lyric:"词：唐恬"},
			{time:"00:07", lyric:"编曲：Daniel Merlot"},
			{time:"00:13", lyric:"时间会告诉你"},
			{time:"00:16", lyric:"给你痛苦的 皈依爱里"},
			{time:"00:19", lyric:"痛是最大天敌"},
			{time:"00:23", lyric:"也是最好的知己"},
			{time:"00:26", lyric:"把黑夜尽头 留给光明"},
			{time:"00:29", lyric:"把失去的 留给风景"},
			{time:"00:31", lyric:"你告别每个你"},
			{time:"00:35", lyric:"收获了完整的自己"},
			{time:"00:38", lyric:"悲伤若不尽兴"},
			{time:"00:41", lyric:"怎修炼温柔爱情"},
			{time:"00:44", lyric:"那伤害你的 从来不曾打败你"},
			{time:"00:50", lyric:"深渊都是倒影"},
			{time:"00:53", lyric:"你看它 它就是你"},
			{time:"00:56", lyric:"往前走吧 时间给你唯一的真理"},
			{time:"01:01", lyric:"相信爱 会等在下一站"},
			{time:"01:06", lyric:"花时间 慢慢来 生命中好与坏 美好痛快"},
			{time:"01:13", lyric:"付出爱 不要再停下来"},
			{time:"01:18", lyric:"为错的 而喝彩 哪个更好的你不从水里火里来 ha…"},
			{time:"01:35", lyric:"The Power of time"},
			{time:"01:40", lyric:"没走完的爱情"},
			{time:"01:43", lyric:"为你学会爱自己"},
			{time:"01:46", lyric:"那离开你的 从来就不属于你"},
			{time:"01:52", lyric:"时间会告诉你"},
			{time:"01:55", lyric:"把眼泪还给你"},
			{time:"01:58", lyric:"往前走吧 每天的太阳都会在升起"},
			{time:"02:03", lyric:"相信爱 会等在下一站"},
			{time:"02:08", lyric:"花时间 慢慢来 生命中好与坏 美好痛快"},
			{time:"02:15", lyric:"付出爱 不要再停下来"},
			{time:"02:20", lyric:"为错的 而喝彩 哪个更好的你不从水里火里来 ha…"},
			{time:"02:37", lyric:"The Power of time"},
			{time:"02:40", lyric:"学会放手才会自由 伤口也是出口"},
			{time:"02:47", lyric:"你在夜里走过 一路上总有错 解脱 生活"},
			{time:"03:01", lyric:"把孤单遗憾都留给爱"},
			{time:"03:07", lyric:"相信爱 会等在下一站"},
			{time:"03:12", lyric:"花时间 慢慢来 生命中好与坏 美好痛快"},
			{time:"03:20", lyric:"付出爱 不要再停下来"},
			{time:"03:25", lyric:"为错的 而喝彩 风吹的山丘 最后变成大海"},
			{time:"03:32", lyric:"别害怕 要勇敢"},
			{time:"03:35", lyric:"别让爱 停下来"},
			{time:"03:38", lyric:"别害怕 你的爱 好与坏一样精彩"},
			{time:"03:44", lyric:"去爱吧 去未来"},
			{time:"03:47", lyric:"转个弯 天更蓝"},
			{time:"03:50", lyric:"别害怕 相信爱 The Power of time"},
			{time:"04:10", lyric:"曾经问的问题"},
			{time:"04:13", lyric:"你等世界回答你"},
			{time:"04:16", lyric:"时间会告诉你"},
			{time:"04:20", lyric:"你会亲手揭开谜底"}]
	},
	{
		id: '3',
		songs: 'The lady feeds her little bird',
		name: '白云',
		src: 'music/白云 - The lady feeds her little bird.mp3',
		alltime: '02:42',
		photo: 'images/swj.jpg',
		lyrics:[
			{time:"00:01" , lyric:"词：爱美丽.迪金森 （美）(Emily Dickinson，1830~1886)"},
			{time:"00:03" , lyric:"曲&吉他&编曲：白云"},
			{time:"00:04" , lyric:"翻译：白云"},
			{time:"00:05" , lyric:"校对：Max（当混电台）"},
			{time:"00:09" , lyric:"觉得这个诗人跟我挺像的 尤其是25岁开始弃绝社交这一点"},
			{time:"00:10" , lyric:"只是在她有生之年 她的作品未能获得青睐 我想我应该没有那么惨"},
			{time:"00:11" , lyric:"因为我有品位那么好的你们"},
			{time:"00:12" , lyric:"谢谢网易的宝宝支持 大家的评论我都看了"},
			{time:"00:12" , lyric:"很多时候 家人泼冷水 朋友的不断开导（再长大一点你就不这样想了你不小了应该想想的父母应该找个稳定的工作巴拉巴拉啦啦啦）让我觉得好孤独"},
			{time:"00:13" , lyric:"你们是我的动力啊"},
			{time:"00:13" , lyric:"当然 那些动不动就爱“开导”我的朋友 我已经和他们绝交啦 我这个人超利落的~~"},
			{time:"00:14" , lyric:"不过话说回来 我不想到死才被人家发现耶~"},
			{time:"00:14" , lyric:"希望可以在活着的时候，最好是年轻的时候。"},
			{time:"00:15" , lyric:"成为一个有钱，漂亮，身材好，并且受人尊敬的"},
			{time:"00:15" , lyric:"为世界创造美好的艺术家。"},
			{time:"00:16" , lyric:"当然梦想丰满 现实骨感。"},
			{time:"00:16" , lyric:"没有关系 不会放弃"},
			{time:"00:17" , lyric:"反正 想一想又不要钱的(*/ω╲*)"},
			{time:"00:17" , lyric:"--白云"},
			{time:"00:19" , lyric:"The lady feeds her little bird 女士喂她的小鸟"},
			{time:"00:28" , lyric:"At rarer intervals – 亲密无间"},
			{time:"00:35" , lyric:"The little bird would not dissent 鸟儿没有不顺从"},
			{time:"00:45" , lyric:"But meekly recognize 而是温柔的许可"},
			{time:"01:09" , lyric:"The lady feeds her little bird 女士喂她的小鸟"},
			{time:"01:18" , lyric:"At rarer intervals – 亲密无间"},
			{time:"01:27" , lyric:"The little bird would not dissent 鸟儿没有不顺从"},
			{time:"01:37" , lyric:"But meekly recognize 而是温柔的许可"},
			{time:"01:46" , lyric:"The gulf between the hand and her 她的手与她之间的隔阂"},
			{time:"01:52" , lyric:"And crumbless and afar 遥远的距离崩塌"},
			{time:"02:00" , lyric:"And fainting, on her yellow knee 就倒在她黄色的膝盖上"},
			{time:"02:16" , lyric:"Fall softly, and adore – 轻轻地 心甘情愿"},
			]		
	},
	{
		id: '4',
		songs: 'I ll Be There',
		name: '汪苏泷',
		src: 'music/汪苏泷 - I ll Be There.mp3',
		alltime: '04:33',
		photo: 'images/wsl.jpg',
		lyrics:[
			{time:"00:00", lyric:"汪苏泷 - I’ll Be There"},
			{time:"00:02", lyric:"电视剧《亲爱的王子大人》主题曲"},
			{time:"00:04", lyric:"作词：杨彤"},
			{time:"00:06", lyric:"作曲：URBAN CLA6IX"},
			{time:"00:08", lyric:"编曲：Urban Cla6ix"},
			{time:"00:10", lyric:"歌词编辑：果果"},
			{time:"00:18", lyric:"I’ll be there"},
			{time:"00:19", lyric:"Oh I’ll be there"},
			{time:"00:26", lyric:"I’ll be there"},
			{time:"00:28", lyric:"Oh I’ll be there"},
			{time:"00:34", lyric:"风吹向哪片海"},
			{time:"00:38", lyric:"我站在这学等待"},
			{time:"00:42", lyric:"等你向我走来oh我的爱"},
			{time:"00:51", lyric:"爱上你的那一天"},
			{time:"00:56", lyric:"全世界突然改变"},
			{time:"01:00", lyric:"相信你也感觉oh我的爱"},
			{time:"01:07", lyric:"我一直站在这等待"},
			{time:"01:12", lyric:"像鱼儿离不开大海"},
			{time:"01:17", lyric:"给我多点时间"},
			{time:"01:21", lyric:"让我在你的身边"},
			{time:"01:25", lyric:"牵着你的手不放开"},
			{time:"01:29", lyric:"感觉爱原来很简单"},
			{time:"01:35", lyric:"你的笑像太阳"},
			{time:"01:39", lyric:"然后轻轻的吻过带走伤"},
			{time:"01:45", lyric:"I’ll be there"},
			{time:"01:47", lyric:"Oh I’ll be there"},
			{time:"01:53", lyric:"I’ll be there"},
			{time:"01:55", lyric:"Oh I’ll be there"},
			{time:"02:03", lyric:"风吹向哪片海"},
			{time:"02:07", lyric:"我站在这学等待"},
			{time:"02:12", lyric:"等你向我走来oh我的爱"},
			{time:"02:21", lyric:"爱上你的那一天"},
			{time:"02:25", lyric:"全世界突然改变"},
			{time:"02:29", lyric:"相信你也感觉oh我的爱"},
			{time:"02:37", lyric:"我一直站在这等待"},
			{time:"02:41", lyric:"像鱼儿离不开大海"},
			{time:"02:47", lyric:"给我多点时间"},
			{time:"02:50", lyric:"让我在你的身边"},
			{time:"02:54", lyric:"牵着你的手不放开"},
			{time:"02:59", lyric:"感觉爱原来很简单"},
			{time:"03:04", lyric:"你的笑像太阳"},
			{time:"03:08", lyric:"然后轻轻的吻过带走伤"},
			{time:"03:15", lyric:"和你走过的一切都是回忆"},
			{time:"03:19", lyric:"我们还能不能够再有继续"},
			{time:"03:23", lyric:"我还等着这一句我爱你"},
			{time:"03:29", lyric:"我一直站在这等待"},
			{time:"03:34", lyric:"像鱼儿离不开大海"},
			{time:"03:39", lyric:"给我多点时间"},
			{time:"03:43", lyric:"让我在你的身边"},
			{time:"03:47", lyric:"牵着你的手不放开"},
			{time:"03:51", lyric:"感觉爱原来很简单"},
			{time:"03:57", lyric:"你的笑像太阳"},
			{time:"04:01", lyric:"然后轻轻的吻过带走伤"},
			{time:"04:06", lyric:"I’ll be there"},
			{time:"04:08", lyric:"Oh I’ll be there"},
			{time:"04:15", lyric:"I’ll be there"},
			{time:"04:17", lyric:"Oh I’ll be there"},
			]
	}
];